Repository Team-Go-Local/go_local_backend, pull requests merged in 2021-02, with the labels that each got.

#6 Set Up Env
  spec/rails_helper.rb
Labels: Setup, backend

#7 Db setup
  .gitignore
  .travis.yml
  Gemfile.lock
  app/models/excursion.rb
  app/models/favorite.rb
  app/models/tag.rb
  app/models/tagging.rb
  app/models/user.rb
  db/migrate/20210224012306_create_users.rb
  db/migrate/20210224014127_create_excursion.rb
  db/migrate/20210224020120_create_tag.rb
  db/migrate/20210224021321_create_favorite.rb
  db/migrate/20210224024043_create_tagging.rb
  db/schema.rb
  spec/features/users/fe_user_will_create_be_user_spec.rb
  spec/models/excursions_spec.rb
  spec/models/favorites_spec.rb
  spec/models/taggings_spec.rb
  spec/models/tags_spec.rb
  spec/models/users_spec.rb
Labels: Setup, backend

#11 Add additional platforms to the Gemfile Lock
  Gemfile.lock
Labels: Setup, Travis CI, backend, bug

#13 Foreign key additions
  db/migrate/20210224235335_remove_users_from_excursions.rb
  db/migrate/20210224235506_add_user_ref_to_excursions.rb
  db/migrate/20210224235959_fix_users_id.rb
  db/migrate/20210225001324_remove_non_primary_key_id_from_user.rb
  db/migrate/20210225010859_change_index_to_foreign_key_on_favorites.rb
  db/migrate/20210225011705_change_index_to_foreign_key_on_excursions.rb
  db/schema.rb
  spec/factories/excursion.rb
  spec/factories/favorite.rb
  spec/factories/tag.rb
  spec/factories/tagging.rb
  spec/factories/user.rb
  spec/models/excursions_spec.rb
  spec/models/favorites_spec.rb
  spec/models/taggings_spec.rb
  spec/models/tags_spec.rb
  spec/models/users_spec.rb
Labels: backend, bug

#14 User create
  app/controllers/api/v1/users_controller.rb
  config/routes.rb
  spec/requests/users/fe_user_will_create_be_user_spec.rb
Labels: backend

#30 Place search request
  README.md
  app/controllers/api/v1/place_search_controller.rb
  app/facades/place_search_facade.rb
  app/services/place_search_service.rb
  config/routes.rb
  db/migrate/20210228045135_add_place_id_to_excursions.rb
  db/schema.rb
  spec/facades/place_search_facade_spec.rb
  spec/fixtures/place_search_result.json
  spec/requests/api/v1/place_search/receive_fe_request_spec.rb
  spec/services/place_search_service_spec.rb
Labels: backend, documentation, iteration 1

#32 create-user
  app/controllers/api/v1/users_controller.rb
Labels: backend, bug
